export const ENDPOINTS = {
  register: 'users/register',
  login: 'users/login',
  logout: 'users/logout',
  catalog: 'data/players?distinct=name&sortBy=name',
  createPlayer: 'data/players',
	likePlayer: 'data/likes',
  details: (playerId: string) => `data/players/${playerId}`,
  edit: (playerId: string) => `data/players/${playerId}`,
  delete: (playerId: string) => `data/players/${playerId}`,
  canLike: (playerId: string, userId: string) => `data/likes?where=playerId%3D%22${playerId}%22%20and%20_ownerId%3D%22${userId}%22&count`,
	likesForPlayer: (playerId: string) => `data/likes?where=playerId%3D%22${playerId}%22&distinct=_ownerId&count`,
  search: (query: string) => `data/players?where=name%20LIKE%20%22${query}%22`,
	getMyPlayers: (userId: string) => `data/players?where=_ownerId%3D%22${userId}%22&sortBy=name`,
};
